import Link from "next/link";

import { api, HydrateClient } from "~/trpc/server";
import { QuickAddButton } from "./_components/quickAddButton";

export default async function Home() {
  const products = await api.product.getAll();

  void api.product.getAll.prefetch();

  return (
    <HydrateClient>
      <main className="min-h-screen bg-gray-50">
              <div className="container mx-auto px-4 py-8">
                      <h1 className="mb-8 text-4xl font-bold text-gray-900">
                                Our Products
                                        </h1>
                                                
                                                        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
                                                                  {products.map((product) => (
                                                                              <Link
                                                                                            key={product.id}
                                                                                                          href={`/products/${product.id}`}
                                                                                                                        className="overflow-hidden rounded-lg bg-white shadow-md transition-all hover:shadow-xl hover:scale-105"
                                                                                                                                    >
                                                                                                                                                  <img
                                                                                                                                                                  src={product.imageUrl}
                                                                                                                                                                                  alt={product.name}
                                                                                                                                                                                                  className="h-48 w-full object-cover"
                                                                                                                                                                                                                />
                                                                                                                                                                                                                              <div className="p-4">
                                                                                                                                                                                                                                              <h2 className="mb-2 text-xl font-semibold text-gray-900">
                                                                                                                                                                                                                                                                {product.name}
                                                                                                                                                                                                                                                                                </h2>
                                                                                                                                                                                                                                                                                                <p className="mb-3 text-sm text-gray-600 line-clamp-2">
                                                                                                                                                                                                                                                                                                                  {product.description}
                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                    <span className="text-2xl font-bold text-blue-600">
                                                                                                                                                                                                                                                                                                                                                                                        ${product.price.toFixed(2)}
                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-medium text-gray-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                {product.category}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <QuickAddButton product={product}/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
    </HydrateClient>
  );
}
