import { headers } from "next/headers";
import { NextResponse } from "next/server";
import { stripe } from "~/lib/store/stripe";
import { db } from "~/server/db";
import Stripe from "stripe";

export async function POST(req: Request) {
  const body = await req.text();
    const headersList = await headers();
      const signature = headersList.get("stripe-signature");

        if (!signature) {
            return NextResponse.json(
                  { error: "No signature found" },
                        { status: 400 }
                            );
                              }

                                let event: Stripe.Event;

                                  try {
                                      // Verify webhook signature
                                          event = stripe.webhooks.constructEvent(
                                                body,
                                                      signature,
                                                            process.env.STRIPE_WEBHOOK_SECRET!
                                                                );
                                                                  } catch (err) {
                                                                      console.error("Webhook signature verification failed:", err);
                                                                          return NextResponse.json(
                                                                                { error: "Invalid signature" },
                                                                                      { status: 400 }
                                                                                          );
                                                                                            }

                                                                                              // Handle different event types
                                                                                                try {
                                                                                                    switch (event.type) {
                                                                                                          case "checkout.session.completed": {
                                                                                                                  const session = event.data.object as Stripe.Checkout.Session;
                                                                                                                          
                                                                                                                                  // Update order status to paid
                                                                                                                                          await db.order.update({
                                                                                                                                                    where: { stripeSessionId: session.id },
                                                                                                                                                              data: { status: "paid" },
                                                                                                                                                                      });
                                                                                                                                                                              
                                                                                                                                                                                      console.log(`✅ Order paid: ${session.id}`);
                                                                                                                                                                                              break;
                                                                                                                                                                                                    }

                                                                                                                                                                                                          case "checkout.session.expired": {
                                                                                                                                                                                                                  const session = event.data.object as Stripe.Checkout.Session;
                                                                                                                                                                                                                          
                                                                                                                                                                                                                                  // Mark order as expired
                                                                                                                                                                                                                                          await db.order.update({
                                                                                                                                                                                                                                                    where: { stripeSessionId: session.id },
                                                                                                                                                                                                                                                              data: { status: "expired" },
                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                      console.log(`⏰ Order expired: ${session.id}`);
                                                                                                                                                                                                                                                                                              break;
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                          case "payment_intent.payment_failed": {
                                                                                                                                                                                                                                                                                                                  const paymentIntent = event.data.object as Stripe.PaymentIntent;
                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                  console.log(`❌ Payment failed: ${paymentIntent.id}`);
                                                                                                                                                                                                                                                                                                                                          // You could send email notification here
                                                                                                                                                                                                                                                                                                                                                  break;
                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                              case "charge.refunded": {
                                                                                                                                                                                                                                                                                                                                                                      const charge = event.data.object as Stripe.Charge;
                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                      // Find order by payment intent and mark as refunded
                                                                                                                                                                                                                                                                                                                                                                                              const paymentIntent = charge.payment_intent as string;
                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                              console.log(`💰 Refund processed: ${paymentIntent}`);
                                                                                                                                                                                                                                                                                                                                                                                                                      // Update order status to refunded
                                                                                                                                                                                                                                                                                                                                                                                                                              break;
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                          default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log(`Unhandled event type: ${event.type}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                          return NextResponse.json({ received: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error("Error processing webhook:", error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return NextResponse.json(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          { error: "Webhook handler failed" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { status: 500 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }