import type { NextRequest, } from "next/server";
import { NextResponse } from "next/server";
import type Stripe from "stripe";
import { stripe } from "~/lib/stripe";
import { db } from "~/server/db";

const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET!;

export const dynamic = 'force-dynamic';

export async function POST(request: NextRequest) {
  const body = await request.text();
    const signature = request.headers.get('stripe-signature');

      if (!signature) {
          return NextResponse.json(
                { error: 'Missing Stripe signature' },
                      { status: 400 }
                          );
                            }

                              let event: Stripe.Event;

                                try {
                                    event = stripe.webhooks.constructEvent(body, signature, webhookSecret);
                                      } catch (err) {
                                          console.error('Webhook signature verification failed:', err);
                                              return NextResponse.json(
                                                    { error: 'Invalid signature' },
                                                          { status: 400 }
                                                              );
                                                                }

                                                                  try {
                                                                      switch (event.type) {
                                                                            case 'checkout.session.completed': {
                                                                                    const session = event.data.object; // No "as" needed
                                                                                            await db.order.update({
                                                                                                      where: { stripeSessionId: session.id },
                                                                                                                data: { status: 'PAID' },
                                                                                                                        });
                                                                                                                                console.log(`Order paid: ${session.id}`);
                                                                                                                                        break;
                                                                                                                                              }

                                                                                                                                                    case 'checkout.session.async_payment_succeeded': {
                                                                                                                                                            const session = event.data.object;
                                                                                                                                                                    await db.order.update({
                                                                                                                                                                              where: { stripeSessionId: session.id },
                                                                                                                                                                                        data: { status: 'PAID' },
                                                                                                                                                                                                });
                                                                                                                                                                                                        console.log(`Async payment succeeded: ${session.id}`);
                                                                                                                                                                                                                break;
                                                                                                                                                                                                                      }

                                                                                                                                                                                                                            case 'checkout.session.async_payment_failed': {
                                                                                                                                                                                                                                    const session = event.data.object;
                                                                                                                                                                                                                                            await db.order.update({
                                                                                                                                                                                                                                                      where: { stripeSessionId: session.id },
                                                                                                                                                                                                                                                                data: { status: 'FAILED' },
                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                console.log(`Async payment failed: ${session.id}`);
                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                    case 'checkout.session.expired': {
                                                                                                                                                                                                                                                                                                            const session = event.data.object;
                                                                                                                                                                                                                                                                                                                    await db.order.update({
                                                                                                                                                                                                                                                                                                                              where: { stripeSessionId: session.id },
                                                                                                                                                                                                                                                                                                                                        data: { status: 'EXPIRED' },
                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                        console.log(`Order expired: ${session.id}`);
                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                            case 'payment_intent.succeeded': {
                                                                                                                                                                                                                                                                                                                                                                                    const paymentIntent = event.data.object;
                                                                                                                                                                                                                                                                                                                                                                                            console.log(`Payment succeeded: ${paymentIntent.id}`);
                                                                                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                case 'payment_intent.payment_failed': {
                                                                                                                                                                                                                                                                                                                                                                                                                        const paymentIntent = event.data.object;
                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(`Payment failed: ${paymentIntent.id}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    case 'payment_intent.canceled': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            const paymentIntent = event.data.object;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`Payment canceled: ${paymentIntent.id}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        case 'charge.succeeded': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const charge = event.data.object;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log(`Charge succeeded: ${charge.id}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case 'charge.failed': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const charge = event.data.object;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log(`Charge failed: ${charge.id}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 'charge.refunded': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const charge = event.data.object;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(`Charge refunded: ${charge.id}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    case 'charge.dispute.created': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const dispute = event.data.object;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`Dispute created: ${dispute.id}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        case 'charge.dispute.closed': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const dispute = event.data.object;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log(`Dispute closed: ${dispute.id}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case 'refund.created': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const refund = event.data.object;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log(`Refund created: ${refund.id}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 'refund.updated': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const refund = event.data.object;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(`Refund updated: ${refund.id}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    case 'refund.failed': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const refund = event.data.object;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`Refund failed: ${refund.id}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(`Unhandled event: ${event.type}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return NextResponse.json({ received: true }, { status: 200 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error('Error processing webhook:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return NextResponse.json(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { error: 'Processing failed' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { status: 500 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }