import { Mail, Truck, Calendar } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";

interface WhatsNextCardProps {
  email: string;
  }

  export function WhatsNextCard({ email }: WhatsNextCardProps) {
    return (
        <Card className="border-primary/30 bg-primary/5">
              <CardHeader>
                      <CardTitle className="text-xl">What Happens Next</CardTitle>
                            </CardHeader>
                                  <CardContent className="space-y-4">
                                          <div className="flex gap-4">
                                                    <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-xl bg-primary/20">
                                                                <Mail className="h-5 w-5 text-primary" />
                                                                          </div>
                                                                                    <div>
                                                                                                <p className="font-semibold text-foreground">Confirmation Email</p>
                                                                                                            <p className="text-sm text-muted-foreground">
                                                                                                                          Check your inbox at {email} for order confirmation
                                                                                                                                      </p>
                                                                                                                                                </div>
                                                                                                                                                        </div>
                                                                                                                                                                <div className="flex gap-4">
                                                                                                                                                                          <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-xl bg-primary/20">
                                                                                                                                                                                      <Truck className="h-5 w-5 text-primary" />
                                                                                                                                                                                                </div>
                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                      <p className="font-semibold text-foreground">Shipping Updates</p>
                                                                                                                                                                                                                                  <p className="text-sm text-muted-foreground">
                                                                                                                                                                                                                                                We&apos;ll send tracking information once your order ships
                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                      <div className="flex gap-4">
                                                                                                                                                                                                                                                                                                <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-xl bg-primary/20">
                                                                                                                                                                                                                                                                                                            <Calendar className="h-5 w-5 text-primary" />
                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                            <p className="font-semibold text-foreground">Estimated Delivery</p>
                                                                                                                                                                                                                                                                                                                                                        <p className="text-sm text-muted-foreground">
                                                                                                                                                                                                                                                                                                                                                                      Arrives within 3-5 business days
                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                          </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                              </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                }