import { z } from "zod";
import { createTRPCRouter, publicProcedure } from "~/server/api/trpc";
import { stripe } from "~/lib/stripe"; // FIXED: Import from your stripe.ts file
import type Stripe from "stripe";

export const orderRouter = createTRPCRouter({
  createCheckoutSession: publicProcedure
      .input(
            z.object({
                    email: z.string().email(),
                            customerName: z.string(),
                                    shippingAddress: z.string(),
                                            city: z.string(),
                                                    postalCode: z.string(),
                                                            country: z.string(),
                                                                    items: z.array(
                                                                              z.object({
                                                                                          productId: z.string(),
                                                                                                      name: z.string(),
                                                                                                                  price: z.number(),
                                                                                                                              quantity: z.number(),
                                                                                                                                        }),
                                                                                                                                                ),
                                                                                                                                                      }),
                                                                                                                                                          )
                                                                                                                                                              .mutation(async ({ ctx, input }) => {
                                                                                                                                                                    // Calculate total
                                                                                                                                                                          const subtotal = input.items.reduce(
                                                                                                                                                                                  (sum, item) => sum + item.price * item.quantity,
                                                                                                                                                                                          0,
                                                                                                                                                                                                );
                                                                                                                                                                                                      const shippingCost = subtotal > 50 ? 0 : 5.99;
                                                                                                                                                                                                            const total = subtotal + shippingCost;

                                                                                                                                                                                                                  // Create order in database - USE UPPERCASE STATUS
                                                                                                                                                                                                                        const order = await ctx.db.order.create({
                                                                                                                                                                                                                                data: {
                                                                                                                                                                                                                                          email: input.email,
                                                                                                                                                                                                                                                    customerName: input.customerName,
                                                                                                                                                                                                                                                              shippingAddress: input.shippingAddress,
                                                                                                                                                                                                                                                                        city: input.city,
                                                                                                                                                                                                                                                                                  postalCode: input.postalCode,
                                                                                                                                                                                                                                                                                            country: input.country,
                                                                                                                                                                                                                                                                                                      totalAmount: total,
                                                                                                                                                                                                                                                                                                                status: "PENDING", // CHANGED: "pending" → "PENDING" (uppercase)
                                                                                                                                                                                                                                                                                                                          items: {
                                                                                                                                                                                                                                                                                                                                      create: input.items.map((item) => ({
                                                                                                                                                                                                                                                                                                                                                    productId: item.productId,
                                                                                                                                                                                                                                                                                                                                                                  name: item.name,
                                                                                                                                                                                                                                                                                                                                                                                price: item.price,
                                                                                                                                                                                                                                                                                                                                                                                              quantity: item.quantity,
                                                                                                                                                                                                                                                                                                                                                                                                          })),
                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                        // Create Stripe line items
                                                                                                                                                                                                                                                                                                                                                                                                                                              const lineItems: Stripe.Checkout.SessionCreateParams.LineItem[] =
                                                                                                                                                                                                                                                                                                                                                                                                                                                      input.items.map((item) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                price_data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            currency: "usd",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        product_data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      name: item.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              unit_amount: Math.round(item.price * 100), // Convert to cents
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  quantity: item.quantity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Add shipping if applicable
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (shippingCost > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              lineItems.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        price_data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    currency: "usd",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                product_data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              name: "Shipping",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      unit_amount: Math.round(shippingCost * 100),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          quantity: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Create Stripe checkout session
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const session = await stripe.checkout.sessions.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            payment_method_types: ["card"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    line_items: lineItems,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mode: "payment",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    success_url: `${process.env.NEXT_PUBLIC_APP_URL}/success?session_id={CHECKOUT_SESSION_ID}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cancel_url: `${process.env.NEXT_PUBLIC_APP_URL}/checkout`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    customer_email: input.email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            metadata: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      orderId: order.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Save Stripe session ID to order
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await ctx.db.order.update({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        where: { id: order.id },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                data: { stripeSessionId: session.id },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return { url: session.url };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  getBySessionId: publicProcedure
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .input(z.object({ sessionId: z.string() }))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .query(async ({ ctx, input }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const order = await ctx.db.order.findUnique({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        where: { stripeSessionId: input.sessionId },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                include: { items: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return order;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });